// Dump the TBQ rotation matrix for embedding in Metal shaders
// Build: cc -O2 -lm -o dump-rotation-matrix dump-rotation-matrix.c
// Run: ./dump-rotation-matrix > rotation_matrix_64.h

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdint.h>

#define QK_TBQ 64

static uint64_t tbq_splitmix64(uint64_t * state) {
    uint64_t z = (*state += 0x9e3779b97f4a7c15ULL);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
    return z ^ (z >> 31);
}

static void tbq_box_muller(uint64_t * state, float * g1, float * g2) {
    uint64_t u1_bits = tbq_splitmix64(state);
    uint64_t u2_bits = tbq_splitmix64(state);
    double u1 = ((double)(u1_bits >> 11) + 0.5) / (double)(1ULL << 53);
    double u2 = ((double)(u2_bits >> 11) + 0.5) / (double)(1ULL << 53);
    double r = sqrt(-2.0 * log(u1));
    *g1 = (float)(r * cos(2.0 * M_PI * u2));
    *g2 = (float)(r * sin(2.0 * M_PI * u2));
}

static uint64_t tbq_seed_for_dim(int d) {
    return 0x54425131ULL ^ (uint64_t)d;
}

static void tbq_generate_rotation(int d, uint64_t seed, float * Q) {
    uint64_t state = seed;
    for (int i = 0; i < d * d - 1; i += 2) {
        tbq_box_muller(&state, &Q[i], &Q[i + 1]);
    }
    if ((d * d) % 2 != 0) {
        float dummy;
        tbq_box_muller(&state, &Q[d * d - 1], &dummy);
    }

    float * v = (float *)malloc(d * sizeof(float));
    float * tau = (float *)malloc(d * sizeof(float));

    for (int j = 0; j < d; j++) {
        float norm_sq = 0.0f;
        for (int i = j; i < d; i++) {
            norm_sq += Q[i * d + j] * Q[i * d + j];
        }
        float norm = sqrtf(norm_sq);
        float sign = Q[j * d + j] >= 0.0f ? 1.0f : -1.0f;

        for (int i = j; i < d; i++) {
            v[i - j] = Q[i * d + j];
        }
        v[0] -= (-sign * norm);

        float vtv = 0.0f;
        for (int i = 0; i < d - j; i++) {
            vtv += v[i] * v[i];
        }
        tau[j] = vtv > 0.0f ? 2.0f / vtv : 0.0f;

        for (int k = j; k < d; k++) {
            float dot = 0.0f;
            for (int i = 0; i < d - j; i++) {
                dot += v[i] * Q[(i + j) * d + k];
            }
            for (int i = 0; i < d - j; i++) {
                Q[(i + j) * d + k] -= tau[j] * v[i] * dot;
            }
        }
    }

    // Re-generate A and do Gram-Schmidt (matching CPU code exactly)
    state = seed;
    float * A = (float *)malloc(d * d * sizeof(float));
    for (int i = 0; i < d * d - 1; i += 2) {
        tbq_box_muller(&state, &A[i], &A[i + 1]);
    }
    if ((d * d) % 2 != 0) {
        float dummy;
        tbq_box_muller(&state, &A[d * d - 1], &dummy);
    }

    for (int j = 0; j < d; j++) {
        for (int i = 0; i < d; i++) {
            Q[i * d + j] = A[i * d + j];
        }
        for (int k = 0; k < j; k++) {
            float dot = 0.0f;
            for (int i = 0; i < d; i++) {
                dot += Q[i * d + k] * Q[i * d + j];
            }
            for (int i = 0; i < d; i++) {
                Q[i * d + j] -= dot * Q[i * d + k];
            }
        }
        float norm = 0.0f;
        for (int i = 0; i < d; i++) {
            norm += Q[i * d + j] * Q[i * d + j];
        }
        norm = sqrtf(norm);
        if (norm > 0.0f) {
            for (int i = 0; i < d; i++) {
                Q[i * d + j] /= norm;
            }
        }
    }

    // Haar sign correction
    for (int j = 0; j < d; j++) {
        float r_jj = 0.0f;
        for (int i = 0; i < d; i++) {
            r_jj += Q[i * d + j] * A[i * d + j];
        }
        if (r_jj < 0.0f) {
            for (int i = 0; i < d; i++) {
                Q[i * d + j] = -Q[i * d + j];
            }
        }
    }

    free(A);
    free(v);
    free(tau);
}

int main(void) {
    const int d = QK_TBQ;
    float * Q = (float *)malloc(d * d * sizeof(float));
    tbq_generate_rotation(d, tbq_seed_for_dim(d), Q);

    printf("// TBQ rotation matrix for d=%d, seed=0x%llx\n", d, tbq_seed_for_dim(d));
    printf("// Generated by dump-rotation-matrix.c — DO NOT EDIT\n");
    printf("// Row-major: Q[i*%d + j]\n\n", d);
    printf("constant float tbq_rotation_64[%d] = {\n", d * d);
    for (int i = 0; i < d * d; i++) {
        if (i % 8 == 0) printf("    ");
        printf("% .8ef,", Q[i]);
        if (i % 8 == 7) printf("\n");
    }
    if ((d * d) % 8 != 0) printf("\n");
    printf("};\n");

    // Verify orthogonality: Q^T Q should be identity
    float max_off = 0.0f, min_diag = 1.0f, max_diag = 0.0f;
    for (int i = 0; i < d; i++) {
        for (int j = 0; j < d; j++) {
            float dot = 0.0f;
            for (int k = 0; k < d; k++) {
                dot += Q[k * d + i] * Q[k * d + j];
            }
            if (i == j) {
                if (dot < min_diag) min_diag = dot;
                if (dot > max_diag) max_diag = dot;
            } else {
                if (fabsf(dot) > max_off) max_off = fabsf(dot);
            }
        }
    }
    fprintf(stderr, "Orthogonality check: diag=[%.6f, %.6f], max_off=%.2e\n",
            min_diag, max_diag, max_off);

    free(Q);
    return 0;
}
